### ISSUE TITLE
Please support BigInt

### ISSUE THREAD

**Issue by joshtriplett** [aemkei/tixy#23]
Current browsers all support the `BigInt` type, but it doesn't seem to work in a tixy program. Would you consider supporting BigInt (the type constructor and the `n` suffix on numeric literals)? That would allow for things like `1n<<i` (use `i` as a bit index).

**Comment by aemkei** [comment]
You cannot mix BigInt and other numeric types. If you need, you have to use `BigInt()` or `Number()`. eg

```js
Number(12345678n & BigInt(1<<i))
```

**Comment by joshtriplett** [comment]
@aemkei I did try converting to BigInt explicitly, but it didn't occur to me that I'd have to convert back to Number at the end to get a result out. That's unfortunate, and takes up much of the character budget.

It would be nice to have a more space-efficient way to use BigInt, but I realize that isn't quite the same as the original request. If this is something you'd be open to considering (e.g. automatically converting the result to a Number), I'd appreciate it.

**Comment by aemkei** [comment]
BigInt is not supported for return values. Everything will be converted using `Number()`.

See: https://tixy.land/?code=x+%3C+8+%3F+1n+%3A+0n
